# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - right_open_manipulator_controller
    - left_open_manipulator_controller
    - maverick_controller

  right_open_manipulator_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_gripper
    action_ns: follow_joint_trajectory
    default: true
  left_open_manipulator_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_gripper
    action_ns: follow_joint_trajectory
    default: true
  maverick_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_gripper
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_gripper
