# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    right_open_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_open_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    maverick_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

right_open_manipulator_controller:
  ros__parameters:
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_open_manipulator_controller:
  ros__parameters:
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
maverick_controller:
  ros__parameters:
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_gripper
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
